# fly.toml app configuration file generated for itapastur-api on 2023-08-24T19:29:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "itapastur-api"
primary_region = "gig"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[processes]
  app = "bundle exec rails server -b 0.0.0.0 -p 3000"